apiVersion: skaffold/v1
kind: Config
metadata:
  name: vice-default-backend
deploy:
  kubectl:
    manifests:
    - k8s/vice-default-backend.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: discoenv/vice-default-backend
  local: {}